openapi: 3.0.1
info:
  title: BlockBet general API
  description: This is a sample API used to illustrate the tooling around an API-first approach.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: dev
paths:
  /blockbet/wallet:
    post:
      summary: create a blockchain wallet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletPostRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletPostResponse'

  /blockbet/wallets:
    get:
      summary: get wallets infos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletsGetResponse'

components:
  schemas:
    WalletsGetResponse:
      type: object
      properties:
        wallets:
          type: array
          items:
            $ref: '#/components/schemas/Wallet'
    Wallet:
      type: object
      required:
        - address
        - publicKey
        - privateKey
        - balance
      properties:
        address:
          type: string
        publicKey:
          type: string
        privateKey:
          type: string
        balance:
          description: account balance in wei
          type: number

    WalletPostRequest:
      type: object
      properties:
        password:
          type: string
    WalletPostResponse:
      type: object
      required:
        - address
        - publicKey
        - privateKey
      properties:
        address:
          type: string
        publicKey:
          type: string
        privateKey:
          type: string