CREATE TABLE IF NOT EXISTS ACCOUNTS(
    ACCOUNT_ID              INT NOT NULL,
    ACCOUNT_NAME            VARCHAR(64) NOT NULL UNIQUE,
    ACCOUNT_PASSWORD        VARCHAR(64) NOT NULL,
    EMAIL                   VARCHAR(128) NOT NULL,
    ENABLED                 BOOLEAN NOT NULL DEFAULT TRUE
    );
CREATE SEQUENCE SEQ_ACCOUNTS START 100;
ALTER TABLE ACCOUNTS ADD CONSTRAINT ACCOUNT_ID PRIMARY KEY (ACCOUNT_ID);


CREATE TABLE IF NOT EXISTS AUTHORITIES(
                                          AUTHORITY_ID            INT NOT NULL,
                                          ACCOUNT_ID              INT NOT NULL,
                                          AUTHORITY               VARCHAR(32) NOT NULL
    );
CREATE SEQUENCE SEQ_AUTHORITIES START 100;
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITY_ID PRIMARY KEY (AUTHORITY_ID);
ALTER TABLE AUTHORITIES ADD CONSTRAINT FK_ACCOUNTS_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID);
ALTER TABLE AUTHORITIES ADD CONSTRAINT UQ_ACCOUNT_ID_AUTHORITY UNIQUE (ACCOUNT_ID, AUTHORITY);


CREATE TABLE IF NOT EXISTS ACCOUNT_DETAILS(
    ACCOUNT_DETAIL_ID       INT NOT NULL,
    PHONE                   VARCHAR(16),
    ADDRESS                 VARCHAR(256),
    NATIONALITY             VARCHAR(2)
    );
CREATE SEQUENCE SEQ_ACCOUNT_DETAILS START 100;
ALTER TABLE ACCOUNT_DETAILS ADD CONSTRAINT ACCOUNT_DETAIL_ID PRIMARY KEY (ACCOUNT_DETAIL_ID);
ALTER TABLE ACCOUNTS ADD COLUMN ACCOUNT_DETAIL_ID INT;
ALTER TABLE ACCOUNTS ADD CONSTRAINT FK_ACCOUNT_DETAILS_ACCOUNT_DETAIL_ID FOREIGN KEY (ACCOUNT_DETAIL_ID) REFERENCES ACCOUNT_DETAILS (ACCOUNT_DETAIL_ID);
