

ALTER TABLE TRANSACTION_RECEIPTS
    ALTER COLUMN BLOCK_HASH DROP NOT NULL;

ALTER TABLE TRANSACTION_RECEIPTS
    ALTER COLUMN BLOCK_NUMBER DROP NOT NULL;

ALTER TABLE TRANSACTION_RECEIPTS
    ALTER COLUMN GAS_USED DROP NOT NULL;

ALTER TABLE TRANSACTION_RECEIPTS
    ALTER COLUMN EFFECTIVE_GAS_PRICE DROP NOT NULL;

ALTER TABLE TRANSACTION_RECEIPTS
    ADD COLUMN IF NOT EXISTS IS_SUCCESS BOOLEAN;
