CREATE TABLE IF NOT EXISTS WALLETS(
    WALLET_ID               INT NOT NULL,
    ADDRESS                 VARCHAR(42) NOT NULL UNIQUE,
    PUBLIC_KEY              VARCHAR(130) NOT NULL UNIQUE,
    PRIVATE_KEY             VARCHAR(66) NOT NULL UNIQUE,
    ACCOUNT_ID              INT NOT NULL
    );
CREATE SEQUENCE SEQ_WALLETS START 100;
ALTER TABLE WALLETS ADD CONSTRAINT WALLET_ID PRIMARY KEY (WALLET_ID);
ALTER TABLE WALLETS ADD CONSTRAINT FK_ACCOUNTS_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID);


