CREATE TABLE IF NOT EXISTS TRANSACTION_RECEIPTS(
    TRANSACTION_RECEIPT_ID      INT             NOT NULL,
    TRANSACTION_TYPE            VARCHAR(32)     NOT NULL,
    HASH                        VARCHAR(66)     NOT NULL UNIQUE,
    FROM_ADDRESS                VARCHAR(42)     NOT NULL,
    TO_ADDRESS                  VARCHAR(42)     NOT NULL,
    BLOCK_HASH                  VARCHAR(66)     NOT NULL,
    BLOCK_NUMBER                INT             NOT NULL,
    GAS_USED                    INT             NOT NULL,
    EFFECTIVE_GAS_PRICE         INT             NOT NULL
    );
CREATE SEQUENCE IF NOT EXISTS SEQ_TRANSACTION_RECEIPTS START 100;
ALTER TABLE TRANSACTION_RECEIPTS ADD CONSTRAINT TRANSACTION_RECEIPT_ID PRIMARY KEY (TRANSACTION_RECEIPT_ID);


